[build]
  publish = "out"
  command = "yarn build && yarn export"

[context.deploy-preview]
  command = "yarn build && yarn export"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cache-Control = '''
    max-age=0,
    must-revalidate'''
    Permissions-Policy = "interest-cohort=()"
