[build]
  publish = "out"
  command = "yarn build"

[context.deploy-preview]
  command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = '''
	  max-age=31536000,
	  includeSubDomains,
	  preload'''
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "script-src 'self';"
    Cache-Control = '''
    max-age=0,
    must-revalidate'''
    Permissions-Policy = "interest-cohort=()"
